

CREATE TABLE [dbo].[EntityCatalog](
	[id_entit] [int] IDENTITY(1,1) NOT NULL,
	[entit_name] [nvarchar](255) NOT NULL,
	[entit_descrip] [nvarchar](255) NOT NULL,
	[entit_active] [bit] NOT NULL,
	[entit_config] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_entit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[entit_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EntityCatalog] ADD  DEFAULT ((1)) FOR [entit_active]
GO


